# Analisis Exploratorio de Datos (EDA)

En este archivo se lleva acabo un analisis exloratorio sobre el dataset de personas desaparecidas ... TODO

**Integrantes:**  
1. José Rubén Alfaro González  
2. Daniela Sanluis
3. Edwin Rodriguez 

**Profesor:**  
Jessica 

**Ayudantes:**  
1. [Nombre del ayudante 1]  
2. [Nombre del ayudante 2]  

**Número de tarea:**  
[Tarea #02]

### Paso 0
Configuramos el ambiente para trabajar. Usaremos librerias como pandas para la lectura de datos

In [28]:
# Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
import warnings

print("Librerias importadas exitosamente")

Librerias importadas exitosamente

### Paso 1
Cargamos el dataset. Además, podemos ver la forma del DS, que contiene 133,886 filas, y 11 columnas. Más información respecto a la información que proporciona cada una de las columnas será dada en el pdf que adjuntamos.

In [29]:
# Cargar dataset
df = pd.read_csv('../data/data_secretariado.csv')
f = df.shape[0]
col = df.shape[1]

print(f"Dataset cargado exitosamente")
print("Número de filas:", f)
print("Número de columnas:", col)

print("Primera inspección: ")
df.head()

Dataset cargado exitosamente
Número de filas: 133887
Número de columnas: 11
Primera inspección:

,ID_VICTIMA,ORIGEN_REPORTE,FECHA_NACIMIENTO,SEXO,FECHA_DESAPARICION,FECHA_REGISTRO,ESTATUS_VICTIMA,CVE_ENT,ENTIDAD,CVE_MUN,MUNICIPIO
0,D49C001E-41E4-45B7-B8FD-D867578F093E,FISCALIA GENERAL DE DURANGO,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,10,DURANGO,999,CONFIDENCIAL
1,2D2B5CD4-7AF7-48C3-887E-72F4C6403863,COMISION LOCAL DE BUSQUEDA DE PERSONAS DEL EST...,1971-06-13,HOMBRE,2025-09-28 04:40:00,2025-09-29 10:00:00,DESAPARECIDA,25,SINALOA,4,CONCORDIA
2,6AE9098C-0C30-4709-9A2C-37F6312CD43E,PROCURADURIA GENERAL DE JUSTICIA DE LA CIUDAD ...,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,9,CIUDAD DE MÉXICO,999,CONFIDENCIAL
3,6B899D2D-F33D-4880-82CD-953FF972B9C3,FISCALIA GENERAL DEL ESTADO BAJA CALIFORNIA,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,2,BAJA CALIFORNIA,999,CONFIDENCIAL
4,3F026638-8169-4CEA-9D9A-E345B6D2D7B6,FISCALIA GENERAL DEL ESTADO BAJA CALIFORNIA,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,CONFIDENCIAL,2,BAJA CALIFORNIA,999,CONFIDENCIAL

### Paso 1.5
Veremos cual es la cantidad de elementos marcados como "CONFIDENCIAL", así como de los valores nulos para luego procesarlos de manera distina, y así poder obtener información útil. Después transformamos las fechas a un formato adecuado.

In [49]:
missing = pd.DataFrame({
    'Columna': df.columns,
    'Valores_Nulos': df.isnull().sum(),
    'Porcentaje': (df.isnull().sum() / len(df)) * 100
}).sort_values('Valores_Nulos', ascending=False)

print("Valores nulos por columna:")
print(missing.to_string(index=False))


confidential = pd.DataFrame({
    'Columna': df.columns,
    'Valores_Confidenciales': [(df[col] == 'CONFIDENCIAL').sum() for col in df.columns],
    'Porcentaje': [(df[col] == 'CONFIDENCIAL').sum() / len(df) * 100 for col in df.columns]
}).sort_values('Valores_Confidenciales', ascending=False)


print("\nValores confidenciales por columna:")
print(confidential.to_string(index=False))

df_clean = df.copy()
date_columns = ['FECHA_NACIMIENTO', 'FECHA_DESAPARICION', 'FECHA_REGISTRO', 'SEXO', 'ESTATUS_VICTIMA', 'MUNICIPIO']
for col in date_columns:
    df_clean[col] = df_clean[col].replace('CONFIDENCIAL', pd.NA)

df_clean.head()


df_clean['FECHA_NACIMIENTO'] = pd.to_datetime(df_clean['FECHA_NACIMIENTO'], errors='coerce')
df_clean['FECHA_DESAPARICION'] = pd.to_datetime(df_clean['FECHA_DESAPARICION'], errors='coerce')
df_clean['FECHA_REGISTRO'] = pd.to_datetime(df_clean['FECHA_REGISTRO'], errors='coerce')

df_clean.head()

Valores nulos por columna:
           Columna  Valores_Nulos  Porcentaje
  FECHA_NACIMIENTO          28887   21.575657
FECHA_DESAPARICION           8160    6.094692
    FECHA_REGISTRO           6097    4.553840
        ID_VICTIMA              0    0.000000
    ORIGEN_REPORTE              0    0.000000
              SEXO              0    0.000000
   ESTATUS_VICTIMA              0    0.000000
           CVE_ENT              0    0.000000
           ENTIDAD              0    0.000000
           CVE_MUN              0    0.000000
         MUNICIPIO              0    0.000000

Valores confidenciales por columna:
           Columna  Valores_Confidenciales  Porcentaje
  FECHA_NACIMIENTO                   49149   36.709315
              SEXO                   49149   36.709315
FECHA_DESAPARICION                   49149   36.709315
    FECHA_REGISTRO                   49149   36.709315
   ESTATUS_VICTIMA                   49149   36.709315
         MUNICIPIO                   49149   36.709315
        ID_VICTIMA                       0    0.000000
    ORIGEN_REPORTE                       0    0.000000
           CVE_ENT                       0    0.000000
           ENTIDAD                       0    0.000000
           CVE_MUN                       0    0.000000

,ID_VICTIMA,ORIGEN_REPORTE,FECHA_NACIMIENTO,SEXO,FECHA_DESAPARICION,FECHA_REGISTRO,ESTATUS_VICTIMA,CVE_ENT,ENTIDAD,CVE_MUN,MUNICIPIO
0,D49C001E-41E4-45B7-B8FD-D867578F093E,FISCALIA GENERAL DE DURANGO,NaT,NaN,NaT,NaT,NaN,10,DURANGO,999,NaN
1,2D2B5CD4-7AF7-48C3-887E-72F4C6403863,COMISION LOCAL DE BUSQUEDA DE PERSONAS DEL EST...,1971-06-13,HOMBRE,2025-09-28 04:40:00,2025-09-29 10:00:00,DESAPARECIDA,25,SINALOA,4,CONCORDIA
2,6AE9098C-0C30-4709-9A2C-37F6312CD43E,PROCURADURIA GENERAL DE JUSTICIA DE LA CIUDAD ...,NaT,NaN,NaT,NaT,NaN,9,CIUDAD DE MÉXICO,999,NaN
3,6B899D2D-F33D-4880-82CD-953FF972B9C3,FISCALIA GENERAL DEL ESTADO BAJA CALIFORNIA,NaT,NaN,NaT,NaT,NaN,2,BAJA CALIFORNIA,999,NaN
4,3F026638-8169-4CEA-9D9A-E345B6D2D7B6,FISCALIA GENERAL DEL ESTADO BAJA CALIFORNIA,NaT,NaN,NaT,NaT,NaN,2,BAJA CALIFORNIA,999,NaN

### Paso 2
Obtenemos un poco de información respecto al dataset. Calculamos la media, moda, mediana, cantidad de valores no-nulos, etc. de los valores de las columnas, así como el tipo de valores que usan (las columnas que lo permiten).

In [54]:
def get_stats(series):
    """
    Obtiene la moda, media (si aplica) y mediana de la columna proporcionada

    Args:
        series: Serie de pandas a analizar
        column: La columna a la que se le desea obtener información

    Returns:
        Media (si es numérica), mediana y moda de la serie
    """
    mode = series.mode().iloc[0] if not series.mode().empty else pd.NA
    median = series.median() if pd.api.types.is_numeric_dtype(series) else pd.NA
    mean = series.mean() if pd.api.types.is_numeric_dtype(series) else pd.NA
    return mean, median, mode

print("Moda de las columnas: ")
mean, median , mode = get_stats(df_clean)
print(mode)

print("\nOtra información del dataset: ")
df_clean.describe(include='all')

Moda de las columnas:
ID_VICTIMA                         0000A344-D137-4261-AB3C-7421869493FF
ORIGEN_REPORTE        PROCURADURIA GENERAL DE JUSTICIA DEL ESTADO DE...
FECHA_NACIMIENTO                                    1900-01-01 00:00:00
SEXO                                                             HOMBRE
FECHA_DESAPARICION                                  1974-01-01 00:00:00
FECHA_REGISTRO                                      2014-09-26 00:00:00
ESTATUS_VICTIMA                                            DESAPARECIDA
CVE_ENT                                                            14.0
ENTIDAD                                                         JALISCO
CVE_MUN                                                           999.0
MUNICIPIO                                                  SE DESCONOCE
Name: 0, dtype: object

Otra información del dataset:

,ID_VICTIMA,ORIGEN_REPORTE,FECHA_NACIMIENTO,SEXO,FECHA_DESAPARICION,FECHA_REGISTRO,ESTATUS_VICTIMA,CVE_ENT,ENTIDAD,CVE_MUN,MUNICIPIO
count,133887,133887,55851,84738,76578,78641,84738,133887.00000,133887,133887.000000,84738
unique,133887,74,NaN,3,NaN,NaN,2,NaN,33,NaN,1553
top,D49C001E-41E4-45B7-B8FD-D867578F093E,PROCURADURIA GENERAL DE JUSTICIA DEL ESTADO DE...,NaN,HOMBRE,NaN,NaN,DESAPARECIDA,NaN,JALISCO,NaN,SE DESCONOCE
freq,1,12085,NaN,64666,NaN,NaN,79881,NaN,14811,NaN,5396
mean,NaN,NaN,1986-09-29 22:29:57.969597,NaN,2017-11-05 18:57:11.744796,2018-03-26 15:08:27.689360,NaN,19.42745,NaN,430.426897,NaN
min,NaN,NaN,0190-05-10 00:00:00,NaN,1961-05-07 12:00:00,1961-05-08 12:00:00,NaN,1.00000,NaN,1.000000,NaN
25%,NaN,NaN,1977-11-18 00:00:00,NaN,2013-10-29 10:30:00,2014-02-21 09:00:00,NaN,12.00000,NaN,22.000000,NaN
50%,NaN,NaN,1988-12-16 00:00:00,NaN,2018-09-21 14:30:00,2019-02-17 21:20:00,NaN,16.00000,NaN,77.000000,NaN
75%,NaN,NaN,1998-04-26 12:00:00,NaN,2023-03-25 03:30:00,2023-03-01 16:00:00,NaN,26.00000,NaN,999.000000,NaN
max,NaN,NaN,3005-08-11 00:00:00,NaN,2025-09-30 07:30:00,2025-10-01 15:18:00,NaN,99.00000,NaN,999.000000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.41155,NaN,472.574020,NaN

### Paso 3